extends: default

ignore:
  - /frontier/swagger/v1/swagger.yaml
  - /frontier/config/database.yml

rules:
  colons:
    max-spaces-after: 10
  line-length:
    max: 120
    ignore: |
      frontier/config/locales
  document-start: disable
