.default: &default
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_HOSTNAME", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  pool: 5

development:
  <<: *default
  database: frontier_development

test:
  <<: *default
  database: frontier_test

production:
  <<: *default
  database: frontier_development
