development: &development
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_HOSTNAME", "localhost") %>
  database: <%= ENV.fetch("POSTGRES_DATABASE", "frontier_#{Rails.env}") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  pool: 5

test:
  <<: *development

production:
  <<: *development
