<% database_config = ENV.key?("SKIP_CONFIGS") ? OpenStruct.new : DatabaseConfig.new %>

.default: &default
  adapter: postgresql
  host: <%= database_config.hostname %>
  username: <%= database_config.username %>
  password: <%= database_config.password %>
  pool: 5

development:
  <<: *default
  database: frontier_development

test:
  <<: *default
  database: frontier_test

production:
  <<: *default
  database: frontier_development
