development: &development
  adapter: postgresql
  host: <%= ENV.fetch("PG_HOST", "localhost") %>
  database: <%= ENV.fetch("PG_DATABASE", "frontier_#{Rails.env}") %>
  username: <%= ENV.fetch("PG_USERNAME", "postgres") %>
  password: <%= ENV.fetch("PG_PASSWORD", "postgres") %>
  pool: 5

test:
  <<: *development

production:
  <<: *development
