---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of my API
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
paths:
  "/api/assignments":
    get:
      summary: List assignments
      tags:
      - assignments
      security:
      - bearer: []
      responses:
        '401':
          description: Unauthorized
        '200':
          description: Operation succeeed
          content:
            application/json:
              examples:
                Operation succeeed:
                  value:
                  - id: 60b87067-c5a3-4340-8a23-836f729983a0
                    course_id: e0846c90-b418-4019-9a85-f96c6b25bfa0
                    title: 1fiv95yuly
                    options:
                      threshold: 0.8
                      ngram_size: 2
                    submissions_count: 
                    created_at: '2024-03-25T01:51:18.457+03:00'
                    updated_at: '2024-03-25T01:51:18.457+03:00'
                    ngram_size: 2
                    threshold: 0.8
                  - id: 2896f738-9d78-4d98-a635-9a2c21af81c8
                    course_id: e0846c90-b418-4019-9a85-f96c6b25bfa0
                    title: 66der3jliz
                    options:
                      threshold: 0.8
                      ngram_size: 2
                    submissions_count: 
                    created_at: '2024-03-25T01:51:18.455+03:00'
                    updated_at: '2024-03-25T01:51:18.455+03:00'
                    ngram_size: 2
                    threshold: 0.8
  "/api/assignments/{id}":
    parameters:
    - name: id
      in: path
      description: Assignment ID
      required: true
      schema:
        type: string
    get:
      summary: Find assignment
      tags:
      - assignments
      security:
      - bearer: []
      responses:
        '401':
          description: Unauthorized
        '200':
          description: Operation succeeed
          content:
            application/json:
              examples:
                Operation succeeed:
                  value:
                    id: 2252ded1-07d1-4051-a409-f8b9e3f0604e
                    course_id: 362a4437-e96e-4c81-a725-cd2e3e9c2016
                    title: ttwaa3unkv
                    options:
                      threshold: 0.8
                      ngram_size: 2
                    submissions_count: 
                    created_at: '2024-03-25T01:51:18.498+03:00'
                    updated_at: '2024-03-25T01:51:18.498+03:00'
                    ngram_size: 2
                    threshold: 0.8
        '404':
          description: Resource not found
  "/api/courses":
    get:
      summary: List courses
      tags:
      - courses
      security:
      - bearer: []
      responses:
        '401':
          description: Unauthorized
        '200':
          description: Operation succeeed
          content:
            application/json:
              examples:
                Operation succeeed:
                  value:
                  - id: cbf63c63-2a6d-496d-8b7b-eff327ca61f4
                    user_id: 264e9a10-a2a6-4ce6-abe9-95d972adeb42
                    title: 4u0a1z6eyq
                    group: reiciendis
                    semester: spring
                    year: 2009
                    created_at: '2024-03-25T01:51:18.535+03:00'
                    updated_at: '2024-03-25T01:51:18.535+03:00'
                  - id: 3883b0e7-9de9-4787-8027-3ffc8a3fbccd
                    user_id: 264e9a10-a2a6-4ce6-abe9-95d972adeb42
                    title: sifji13g4r
                    group: explicabo
                    semester: fall
                    year: 2001
                    created_at: '2024-03-25T01:51:18.537+03:00'
                    updated_at: '2024-03-25T01:51:18.537+03:00'
    post:
      summary: Create new course
      tags:
      - courses
      security:
      - bearer: []
      parameters: []
      responses:
        '401':
          description: Unauthorized
        '201':
          description: Course created
          content:
            application/json:
              examples:
                Course created:
                  value:
                    id: 844fb548-9985-4c2f-8c0b-0fe27be34d83
                    user_id: ac630c9b-5963-489d-912d-b5053da62d9f
                    title: course-1
                    group: foobar
                    semester: spring
                    year: 2024
                    created_at: '2024-03-25T01:51:18.559+03:00'
                    updated_at: '2024-03-25T01:51:18.559+03:00'
        '422':
          description: Invalid request payload
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                group:
                  type: string
                semester:
                  type: string
                  enum:
                  - spring
                  - fall
                title:
                  type: string
                  mixLength: 3
                  maxLnegth: 40
        required: true
