require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/bundle"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Style/Documentation:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineLength:
  Max: 140
  Exclude:
    - config/initializers/devise.rb

Metrics/BlockLength:
  Exclude:
    - app/admin/**/*.rb
    - lib/tasks/**/*.{rake,rb}
    - spec/**/*_spec.rb
    - db/**/*.rb

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Rails/Inquiry:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/api/**/*_spec.rb

RSpec/VariableName:
  AllowedPatterns:
    - ^Authorization
