name: Lint
on: push

jobs:
  lint-ruby:
    name: lint-ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
      - name: Run linter
        working-directory: frontier
        env:
          RAILS_ENV: test
        run: bundle install && bundle exec rubocop

