name: Test
"on": push

jobs:
  test-frontier:
    name: test-frontier
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: frontier_ci
          POSTGRES_USER: frontier_ci_user
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
      - name: Setup test database
        working-directory: frontier
        env:
          RAILS_ENV: test
          PGHOST: localhost
          POSTGRES_DATABASE: frontier_ci
          POSTGRES_USERNAME: frontier_ci_user
          POSTGRES_PASSWORD: postgres
        run: bundle install && bundle exec rails db:create db:migrate
      - name: Run tests
        working-directory: frontier
        env:
          POSTGRES_HOSTNAME: localhost
          POSTGRES_DATABASE: frontier_ci
          POSTGRES_USERNAME: frontier_ci_user
          POSTGRES_PASSWORD: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_ENV: test
        run: bundle exec rspec

      - uses: joshmfrankel/simplecov-check-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: frontier/coverage/.last_run.json
